# Generated by Django 5.0.6 on 2024-06-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='info',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='true_or_false',
            field=models.BooleanField(default=True),
        ),
    ]
