# Generated by Django 5.0.6 on 2024-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_new_info_new_true_or_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
